# Basic CI/CD Configuration File
project_language: "python"
runUnitTests: true
runLintTests: true

tool_for_unit_testing:
  python: "pytest"
tool_for_lint_testing:
  python: "pylint"

# Basic Notification Configuration
notifications:
  email:
    recipients: 
      - "smanprit022@gmail.com"
  # slack:
  #   channel: "#builds"

# # Quality Gates (UNSTABLE vs FAILED)
# quality_gates:
#   lint:
#     fail_on_error: false     # false = UNSTABLE, true = FAILED
#     generate_report: true    # Generate detailed lint report
#   unit_test:
#     fail_on_error: false     # false = UNSTABLE, true = FAILED
#     generate_report: true    # Generate detailed test report

# Report Configuration
reports:
  pytest:
    enabled: true
    results_path: "test-results"
    report_path: "htmlcov"
    coverage: true
  lint:
    enabled: true
    pylint_output: "pylint-report.txt"
    format: "text"
